version: '3.8'

# Railway Docker Compose Configuration
# This is used by Railway for multi-service deployments

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    environment:
      - SPRING_PROFILES_ACTIVE=production
      - SERVER_PORT=8080
      - HF_API_KEY=${HF_API_KEY}
      - RAILWAY_ENVIRONMENT=production
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    environment:
      - API_BASE_URL=https://${RAILWAY_BACKEND_URL}
    ports:
      - "80:80"
    depends_on:
      backend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped

# Railway will automatically handle networking
networks:
  default:
    name: railway-network