# Railway.app deployment configuration for QA Automation Service Hub
# Single service configuration (Backend + Frontend static files)

[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile.backend"

[deploy]
startCommand = "java -Xmx512m -Xms256m -jar app.jar"
healthcheckPath = "/actuator/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment variables (will be set in Railway dashboard)
# HF_API_KEY=your-huggingface-api-key
# SPRING_PROFILES_ACTIVE=production
# SERVER_PORT=8080