global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # QA Automation Backend
  - job_name: 'qa-automation-backend'
    static_configs:
      - targets: ['backend:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    scrape_timeout: 5s
    scheme: http

  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Optional: Add more targets as needed
  # - job_name: 'spring-boot-admin'
  #   static_configs:
  #     - targets: ['admin-server:8080']
  #   metrics_path: '/actuator/prometheus'

# Alerting configuration (optional)
# alerting:
#   alertmanagers:
#     - static_configs:
#         - targets:
#           # - alertmanager:9093

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'
# rule_files:
#   - "alert_rules.yml"