global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']
    scrape_interval: 5s

  - job_name: 'spring-boot-admin'
    static_configs:
      - targets: ['admin-server:8080']
    scrape_interval: 10s